# Wrap all comments and lines to 80 characters
chain_width                   = 100
edition                       = "2021"
max_width                     = 100
single_line_if_else_max_width = 100
use_small_heuristics          = "Max"

### Unstable ###

# comment_width     = 95
# fn_single_line    = true
# unstable_features = true
# wrap_comments     = true
